/* words.js — typerun word pools */
window.TYPERUN_WORDS = {
  tiers: [

    // ── Tier 0: 3-5 chars — levels 1-2 ──────────────────────────────────────
    [
      'cat','run','jump','type','fire','fast','dash','kick','boom','glow',
      'zing','flip','spin','zap','hop','snap','ping','skip','drop','fog',
      'jet','dot','pop','hex','vim','bit','brew','clan','dusk','fizz',
      'gust','hush','iris','jinx','game','code','race','path','wolf','duck',
      'tank','frog','bolt','jolt','curl','tick','rock','lock','silk','mint',
      'hint','dunk','funk','punk','sunk','wink','sink','link','pink','gulp',
      'melt','felt','belt','halt','salt','walk','hulk','runt','hunt','lurk',
      'quip','grip','trip','whip','slip','clip','swap','wrap','clap','trap',
      'slap','chap','ship','grit','spit','knit','quit','emit','exit','gist',
      'list','mist','fist','just','bust','dust','lust','must','rust','hurt',
      'blurt','flirt','skirt','shirt','pact','raft','loft','buff','huff',
      'puff','cuff','tiff','cliff','sniff','crow','blow','flow','slow','show',
      'grow','draw','flaw','claw','plod','smog','blob','snob','knob','crab',
      'grab','drab','slab','stab','flub','stub','snub','grub','club','thud',
      'spud','crud','plum','drum','slum','scum','glum','stun','bun','pun',
      'nun','gun','fun','sun','run','ton','won','son','don','con',
      'bin','din','fin','gin','kin','pin','sin','tin','win','yin',
      'bay','day','gay','hay','jay','kay','lay','may','nay','pay',
      'ray','say','way','yay','fly','fry','dry','pry','try','cry',
      'guy','buy','dye','eye','lie','pie','tie','rye','bye','aye',
    ],

    // ── Tier 1: 5-7 chars — levels 3-4 ──────────────────────────────────────
    [
      'speed','words','typing','planet','burst','flame','storm','blaze','laser',
      'power','pixel','dodge','craft','forge','vortex','charge','sprint','runner',
      'turbo','strike','hammer','shield','motion','stream','rhythm','signal',
      'blazer','bridge','chrome','danger','emblem','factor','gadget','hurdle',
      'ignite','jargon','kindle','lancer','matrix','neural','oracle','portal',
      'frost','blend','quest','twist','pluck','snarl','growl','scout','found',
      'hound','round','sound','bound','pound','mount','count','grunt','front',
      'blunt','stunt','joint','bench','clamp','stomp','spark','stark','march',
      'torch','surge','purge','verge','merge','large','barge','scope','slope',
      'swoop','crook','brook','flock','clock','block','shock','knock','stock',
      'ghost','roast','coast','toast','feast','beast','tread','bread','dread',
      'bleed','greed','breed','quick','thick','flick','slick','brick','trick',
      'click','draft','shaft','swift','drift','shift','tough','rough','enough',
      'gruff','stuff','snuff','fluff','bluff','stiff','cleft','theft','bereft',
      'aloft','dwarf','plunge','cringe','fringe','launch','blanch','stance',
      'prance','glance','trance','chafe','wrath','froth','broth','cloth','sloth',
      'crisp','clasp','grasp','wasp','lisp','gasp','rasp','wisp',
      'glitch','stitch','twitch','snitch','switch','clutch','crutch','hutch',
      'smash','clash','brash','crash','flash','gnash','splash','thrash',
      'brace','grace','place','space','trace','brace','chase','phase',
      'blaze','craze','glaze','graze','phase','blaze','amaze','daze',
      'crimp','chimp','blimp','skimp','shrimp','clump','stump','trump',
      'frond','blond','beyond','bond','fond','pond','wand','bland','brand',
      'grand','stand','strand','expand','island','demand','command',
      'prism','schism','chasm','spasm','rhythm','axiom','idiom',
      'brink','clink','drink','flink','shrink','slink','stink','think','wink',
      'brawl','crawl','drawl','prowl','growl','scrawl','sprawl','trawl',
      'frown','brown','clown','crown','drown','gown','town','renown',
    ],

    // ── Tier 2: 7-10 chars — levels 5-6 ─────────────────────────────────────
    [
      'keyboard','champion','obstacle','lightning','survival','velocity','sequence',
      'accuracy','marathon','endurance','cascading','wordsmith','reaction','countdown',
      'precision','threshold','electrify','hyperdash','trackback','breakaway',
      'character','dashboard','flagship','generator','hurricane','juggernaut',
      'absolute','abstract','calendar','capacity','cellular','chemical',
      'circular','critical','cylinder','decision','describe','diameter',
      'disaster','discover','distance','distinct','doctrine','document',
      'dominant','drawback','economic','electric','electron','embedded',
      'emission','employee','entirely','equality','eruption','essential',
      'evaluate','evidence','evolving','exchange','exercise','explicit',
      'exposure','external','familiar','festival','firmware','flashback',
      'fracture','fragment','galactic','geometry','gradient','graphite',
      'hardware','harmonic','hologram','humanoid','hypnotic','identity',
      'ignition','illusion','immortal','increase','indicate','infantry',
      'infinite','integral','interval','invasion','involved','isolated',
      'language','latitude','layering','leverage','magnetic','manifest',
      'membrane','metallic','minimize','navigate','negative','offshore',
      'optimize','ordinary','outbreak','overcome','override','parallel',
      'periodic','physical','platform','playback','portable','positive',
      'powerful','pressure','probable','progress','protocol','reactive',
      'recharge','redefine','redirect','regulate','reliable','research',
      'resource','response','restrict','reversal','rollback','rotation',
      'scaffold','scanning','sentinel','simulate','singular','skeleton',
      'software','specimen','spectrum','standard','starfall','strategy',
      'strength','structure','symbolic','terminal','throttle','timecode',
      'topology','tracking','transfer','turbulent','ultimate','underway',
      'universe','unstable','validate','variable','vertical','virtual',
      'warrior','waterfall','wavelength','windfall','wireless','workshop',
      'worldwide','meltdown','backstab','outbreak','gridlock','fallback',
      'override','deadlock','firestorm','blastoff','lockdown','shutdown',
      'overload','burndown','tailspin','freefall','breakout','jailbreak',
    ],

    // ── Tier 3: 10-14 chars — level 7+ ──────────────────────────────────────
    [
      'catastrophic','breakthrough','thunderstorm','unbelievable','professional',
      'relationship','particularly','experimental','championship','extraordinary',
      'underground','independent','spectacular','investigate','magnificent',
      'opportunity','programming','protagonist','recognition','responsible',
      'traditional','transmission','typewritten','unstoppable','comfortable',
      'combination','competition','composition','computation','conditional',
      'consequence','consumption','corporation','counterpart','development',
      'dimensional','distinction','environment','established','explanation',
      'exploration','fingerprint','fundamental','generations','imagination',
      'immediately','information','inspiration','institution','interaction',
      'interesting','limitations','maintenance','measurement','microscopic',
      'nightmarish','observation','performance','perspective','probability',
      'realization','restriction','scholarship','substantial','supernatural',
      'uncertainty','unfortunate','vaccination','acceleration','catastrophe',
      'interference','hypothetical','exhilarating','entertainment','establishment',
      'productivity','construction','contribution','coordination','corresponding',
      'discomfort','effectively','efficiently','electricity','elimination',
      'equilibrium','evacuation','exaggeration','fabrication','fluorescent',
      'fortification','generosity','hallucinate','illuminated','illustration',
      'imagination','immovable','impractical','incompetent','indestructible',
      'inevitable','innumerable','intellectual','intelligence','intermission',
      'intimidation','jurisdiction','masterpiece','mathematical','millennia',
      'misdirection','modification','neverending','notification','outperform',
      'perpetuate','photographic','precipitate','preposterous','quantifiable',
      'recalibrate','recognizable','regeneration','reinstating','remembrance',
      'replacement','reprogrammed','resurrection','satisfaction','spectacular',
      'stereotypical','subordinate','suffocation','supplemental','surveillance',
      'systematically','technological','telecommunications','turbulence',
      'uncompromising','underdeveloped','unforeseeable','unprecedented',
      'unprecedented','catastrophically','wordprocessor','typographical',
    ],
  ],

  hazards: [
    'trap','void','bait','fake','lure','hook','snag','doom',
    'null','dead','bomb','jinx','sham','evade','decoy',
    'avert','dodge','feint','bluff','mirage','deceit',
  ],
};
